---
redis_enabled: true
glances_enabled: true
opengist_enabled: true
paperless_enabled: true
restic_rest_server_enabled: true
backups_enabled: true
navidrome_enabled: true
caddy_enabled: true
cloudflared_enabled: true
openwebui_enabled: true
trilium_enabled: true
memos_enabled: true
tailscaled_enabled: true


caddy_caddyfile: |
  {
    http_port {{ caddy_http_port }}
    https_port {{ caddy_https_port }}
    auto_https off
  }


  # Cloudflare Tunnel
  http://gist.700457.xyz {
    # Opengist
    reverse_proxy http://localhost:{{ opengist_port }}
  }


  # Tailscale
  http://glances.ts.700457.xyz {
    # Glances
    reverse_proxy http://localhost:61208
  }

  http://{{ paperless_ngx_hostname }} {
    # Paperless-ngx
    reverse_proxy http://localhost:{{ paperless_ngx_port }}
  }

  http://restic.ts.700457.xyz {
    # restic rest-server
    reverse_proxy http://localhost:{{ restic_rest_server_port }}
  }

  http://music.ts.700457.xyz {
    # Navidrome
    reverse_proxy http://localhost:{{ navidrome_port }}
  }

  http://chat.ts.700457.xyz {
    # Open WebUI
    reverse_proxy http://localhost:{{ openwebui_port }}
  }

  http://notes.ts.700457.xyz {
    # Trilium Notes
    reverse_proxy http://localhost:{{ trilium_port }}
  }

  http://memos.ts.700457.xyz {
    # Trilium Notes
    reverse_proxy http://localhost:{{ memos_port }}
  }
